In [1]:
import os
import polars as pl
import datetime
import decimal
import uuid
from pyspark.sql import functions as F
from pyspark.sql.functions import col, date_trunc, when
from src.utils.config import setup_clickhouse_client
from src.utils.spark import get_spark

spark = get_spark()

ch_user = os.getenv('CLICKHOUSE_USER')
ch_password = os.getenv('CLICKHOUSE_PW')
ch_host = os.getenv('CLICKHOUSE_HOST')
client = setup_clickhouse_client(ch_user, ch_password, ch_host)

In [3]:
def convert_row(row):
    return [
        x.isoformat() if isinstance(x, datetime.datetime)
        else float(x) if isinstance(x, decimal.Decimal)
        else str(x) if isinstance(x, uuid.UUID) 
        else ','.join(map(str, x)) if isinstance(x, list)
        else x
        for x in row
    ]

In [10]:
# Fetch flights data
flights_query = "SELECT * FROM aviation_flights order by (dep_scheduled_time, dep_actual_time, arr_scheduled_time, arr_actual_time)"
flights_result = client.query(flights_query).result_rows
flights_columns = client.query(flights_query).column_names
flights_result = [convert_row(row) for row in flights_result]

# Create spark DataFrame
flights_pdf = pl.DataFrame(flights_result, schema=flights_columns, orient='row')

print(f"Total flight records retrieved: {len(flights_pdf)}")
flights_pdf.head(5)

Total flight records retrieved: 129442

shape: (5, 14)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ insert_tim ┆ flight_ty ┆ status ┆ … ┆ arr_actua ┆ arr_delay ┆ codeshare ┆ codeshare │
│ ---        ┆ e          ┆ pe        ┆ ---    ┆   ┆ l_time    ┆ _mins     ┆ d_airline ┆ d_flight_ │
│ str        ┆ ---        ┆ ---       ┆ str    ┆   ┆ ---       ┆ ---       ┆ ---       ┆ number    │
│            ┆ str        ┆ str       ┆        ┆   ┆ str       ┆ i64       ┆ str       ┆ ---       │
│            ┆            ┆           ┆        ┆   ┆           ┆           ┆           ┆ str       │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 6d6eb7ea-6 ┆ 2026-04-10 ┆ arrival   ┆ landed ┆ … ┆ 2026-02-2 ┆ 0         ┆           ┆           │
│ 94b-4050-b ┆ T14:49:47. ┆           ┆        ┆   ┆ 8T23:35:0 ┆           ┆           ┆           │
│ 2bf-2a5cb5 ┆ 510000+08: ┆           ┆        ┆   ┆ 0         ┆           ┆           ┆           │
│ …          ┆ …          ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│ 3c71e857-3 ┆ 2026-04-10 ┆ arrival   ┆ landed ┆ … ┆ 2026-03-0 ┆ 0         ┆           ┆           │
│ e4f-41cb-9 ┆ T14:50:16. ┆           ┆        ┆   ┆ 1T09:33:0 ┆           ┆           ┆           │
│ fcf-0130d2 ┆ 484000+08: ┆           ┆        ┆   ┆ 0         ┆           ┆           ┆           │
│ …          ┆ …          ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│ 2d6be94c-3 ┆ 2026-04-10 ┆ arrival   ┆ landed ┆ … ┆ 2026-03-0 ┆ 0         ┆           ┆           │
│ 555-4311-9 ┆ T14:50:16. ┆           ┆        ┆   ┆ 1T09:25:0 ┆           ┆           ┆           │
│ 5aa-13c80e ┆ 484000+08: ┆           ┆        ┆   ┆ 0         ┆           ┆           ┆           │
│ …          ┆ …          ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│ 70b0b485-e ┆ 2026-04-10 ┆ arrival   ┆ landed ┆ … ┆ 2026-03-0 ┆ 0         ┆           ┆           │
│ fc0-4753-8 ┆ T14:50:24. ┆           ┆        ┆   ┆ 1T10:44:0 ┆           ┆           ┆           │
│ 280-a4c9e5 ┆ 761000+08: ┆           ┆        ┆   ┆ 0         ┆           ┆           ┆           │
│ …          ┆ …          ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│ d70fe84e-6 ┆ 2026-04-10 ┆ arrival   ┆ landed ┆ … ┆ 2026-03-0 ┆ 34        ┆           ┆           │
│ 94d-4020-9 ┆ T14:50:28. ┆           ┆        ┆   ┆ 1T12:49:0 ┆           ┆           ┆           │
│ 7e6-6a879e ┆ 880000+08: ┆           ┆        ┆   ┆ 0         ┆           ┆           ┆           │
│ …          ┆ …          ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [11]:
weather_query = "SELECT * FROM historical_weather_data order by date_observed"

weather_result = client.query(weather_query).result_rows
weather_result = [convert_row(row) for row in weather_result]
weather_columns = client.query(weather_query).column_names

weather_pdf = pl.DataFrame(weather_result, schema=weather_columns, orient='row')

print(f"Total weather records retrieved: {len(weather_pdf)}")
weather_pdf.head(5)

Total weather records retrieved: 966

shape: (5, 16)
┌────────────┬────────────┬────────────┬───────────┬───┬─────────┬─────────┬───────────┬───────────┐
│ id         ┆ insert_tim ┆ date_obser ┆ current_t ┆ … ┆ rain_1h ┆ rain_3h ┆ weather_m ┆ weather_d │
│ ---        ┆ e          ┆ ved        ┆ emp       ┆   ┆ ---     ┆ ---     ┆ ain       ┆ esc       │
│ str        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ f64     ┆ f64     ┆ ---       ┆ ---       │
│            ┆ str        ┆ str        ┆ f64       ┆   ┆         ┆         ┆ str       ┆ str       │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═════════╪═════════╪═══════════╪═══════════╡
│ 5cc74c3f-b ┆ 2026-04-10 ┆ 2026-02-28 ┆ 27.79     ┆ … ┆ 0.0     ┆ 0.0     ┆ Clouds    ┆ broken    │
│ 81e-48c6-a ┆ T12:45:38. ┆ T16:00:00  ┆           ┆   ┆         ┆         ┆           ┆ clouds    │
│ c3f-0c2d65 ┆ 549000+08: ┆            ┆           ┆   ┆         ┆         ┆           ┆           │
│ …          ┆ …          ┆            ┆           ┆   ┆         ┆         ┆           ┆           │
│ ebec1e01-2 ┆ 2026-04-10 ┆ 2026-02-28 ┆ 27.22     ┆ … ┆ 0.0     ┆ 0.0     ┆ Clouds    ┆ broken    │
│ b88-42cb-8 ┆ T12:45:38. ┆ T17:00:00  ┆           ┆   ┆         ┆         ┆           ┆ clouds    │
│ 772-f39638 ┆ 549000+08: ┆            ┆           ┆   ┆         ┆         ┆           ┆           │
│ …          ┆ …          ┆            ┆           ┆   ┆         ┆         ┆           ┆           │
│ eb52ac12-8 ┆ 2026-04-10 ┆ 2026-02-28 ┆ 27.22     ┆ … ┆ 0.0     ┆ 0.0     ┆ Clouds    ┆ broken    │
│ 740-498b-a ┆ T12:45:38. ┆ T18:00:00  ┆           ┆   ┆         ┆         ┆           ┆ clouds    │
│ e0d-aab525 ┆ 549000+08: ┆            ┆           ┆   ┆         ┆         ┆           ┆           │
│ …          ┆ …          ┆            ┆           ┆   ┆         ┆         ┆           ┆           │
│ 7a20d0bb-1 ┆ 2026-04-10 ┆ 2026-02-28 ┆ 27.22     ┆ … ┆ 0.0     ┆ 0.0     ┆ Clouds    ┆ broken    │
│ 920-4d87-9 ┆ T12:45:38. ┆ T19:00:00  ┆           ┆   ┆         ┆         ┆           ┆ clouds    │
│ 1cc-0afaff ┆ 549000+08: ┆            ┆           ┆   ┆         ┆         ┆           ┆           │
│ …          ┆ …          ┆            ┆           ┆   ┆         ┆         ┆           ┆           │
│ b2b7e1f2-5 ┆ 2026-04-10 ┆ 2026-02-28 ┆ 26.93     ┆ … ┆ 0.0     ┆ 0.0     ┆ Clouds    ┆ broken    │
│ e3d-445f-8 ┆ T12:45:38. ┆ T20:00:00  ┆           ┆   ┆         ┆         ┆           ┆ clouds    │
│ c5c-a3363c ┆ 549000+08: ┆            ┆           ┆   ┆         ┆         ┆           ┆           │
│ …          ┆ …          ┆            ┆           ┆   ┆         ┆         ┆           ┆           │
└────────────┴────────────┴────────────┴───────────┴───┴─────────┴─────────┴───────────┴───────────┘

In [12]:
print('Prepared flights and weather data for merging.')

# Filter out cancelled and unknown status flights
valid_statuses = ['cancelled', 'unknown']
flights_filtered = flights_pdf.filter(~pl.col('status').is_in(valid_statuses)) \
                    .unique(subset=['flight_type', 'status', 'iata_number', 'airline_name', 
                                    'dep_scheduled_time', 'arr_scheduled_time', 'dep_actual_time', 'arr_actual_time'],
                                    keep='first')

print(f"Flight records after filtering: {len(flights_filtered)}")

Prepared flights and weather data for merging.
Flight records after filtering: 126064

In [13]:
# Create hour columns for both departure and arrival times
flights_filtered = flights_filtered.with_columns(
    pl.col('dep_scheduled_time').str.to_datetime().dt.truncate('1h').alias('dep_hour'),
    pl.col('arr_scheduled_time').str.to_datetime().dt.truncate('1h').alias('arr_hour')
)

# Split into departure and arrival flights for conditional merging 
departure_flights = flights_filtered.filter(pl.col('flight_type') == 'departure')
arrival_flights = flights_filtered.filter(pl.col('flight_type') == 'arrival')

print(f"\nDeparture flights: {len(departure_flights)}, Arrival flights: {len(arrival_flights)}")
departure_flights.head(3)
arrival_flights.head(3)

Departure flights: 63390, Arrival flights: 62674

shape: (3, 16)
┌────────────┬────────────┬───────────┬────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ id         ┆ insert_tim ┆ flight_ty ┆ status ┆ … ┆ codeshare ┆ codeshare ┆ dep_hour  ┆ arr_hour  │
│ ---        ┆ e          ┆ pe        ┆ ---    ┆   ┆ d_airline ┆ d_flight_ ┆ ---       ┆ ---       │
│ str        ┆ ---        ┆ ---       ┆ str    ┆   ┆ ---       ┆ number    ┆ datetime[ ┆ datetime[ │
│            ┆ str        ┆ str       ┆        ┆   ┆ str       ┆ ---       ┆ μs]       ┆ μs]       │
│            ┆            ┆           ┆        ┆   ┆           ┆ str       ┆           ┆           │
╞════════════╪════════════╪═══════════╪════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 53687328-1 ┆ 2026-04-10 ┆ arrival   ┆ landed ┆ … ┆           ┆           ┆ 2026-03-0 ┆ 2026-03-0 │
│ 109-497b-b ┆ T14:52:49. ┆           ┆        ┆   ┆           ┆           ┆ 3         ┆ 3         │
│ a22-404e0d ┆ 876000+08: ┆           ┆        ┆   ┆           ┆           ┆ 08:00:00  ┆ 11:00:00  │
│ …          ┆ …          ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│ 6a23a8c1-7 ┆ 2026-04-10 ┆ arrival   ┆ landed ┆ … ┆ singapore ┆ sq601     ┆ 2026-03-0 ┆ 2026-03-0 │
│ b51-405b-a ┆ T14:59:45. ┆           ┆        ┆   ┆ airlines  ┆           ┆ 8         ┆ 8         │
│ b37-249cfc ┆ 393000+08: ┆           ┆        ┆   ┆           ┆           ┆ 08:00:00  ┆ 14:00:00  │
│ …          ┆ …          ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
│ 5e99238a-3 ┆ 2026-04-10 ┆ arrival   ┆ landed ┆ … ┆           ┆           ┆ 2026-03-0 ┆ 2026-03-0 │
│ d75-42ab-8 ┆ T14:59:17. ┆           ┆        ┆   ┆           ┆           ┆ 8         ┆ 8         │
│ 12e-510024 ┆ 786000+08: ┆           ┆        ┆   ┆           ┆           ┆ 03:00:00  ┆ 06:00:00  │
│ …          ┆ …          ┆           ┆        ┆   ┆           ┆           ┆           ┆           │
└────────────┴────────────┴───────────┴────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [14]:
# need to trace why insert_time, date_observed, and weather_hour, weather_main, weather_desc are null after conversion to polars
weather_pdf = weather_pdf.with_columns(
    pl.col('date_observed').str.to_datetime().dt.truncate('1h').alias('weather_hour') 
)

# Deduplicate weather data: keep only one record per hour
# find out how to concatenate unique weather conditions and descriptions for duplicate hour/date entries
weather_pdf = weather_pdf.group_by(['weather_hour', 'date_observed']).agg(
    [
        pl.exclude(["id", "insert_time", "weather_main", "weather_desc", "weather_hour", "date_observed"]).mean(),

        pl.col("weather_main")
        .drop_nulls()
        .unique()
        .str.join(", ")
        .alias("weather_main"),

        pl.col("weather_desc")
        .drop_nulls()
        .unique()
        .str.join(", ")
        .alias("weather_desc"),
    ]
) 
print(f"Weather records by hour: {len(weather_pdf)}")

weather_pdf.head(3)

Weather records by hour: 960

shape: (3, 15)
┌────────────┬────────────┬────────────┬───────────┬───┬─────────┬─────────┬───────────┬───────────┐
│ weather_ho ┆ date_obser ┆ current_te ┆ feels_lik ┆ … ┆ rain_1h ┆ rain_3h ┆ weather_m ┆ weather_d │
│ ur         ┆ ved        ┆ mp         ┆ e_temp    ┆   ┆ ---     ┆ ---     ┆ ain       ┆ esc       │
│ ---        ┆ ---        ┆ ---        ┆ ---       ┆   ┆ f64     ┆ f64     ┆ ---       ┆ ---       │
│ datetime[μ ┆ str        ┆ f64        ┆ f64       ┆   ┆         ┆         ┆ str       ┆ str       │
│ s]         ┆            ┆            ┆           ┆   ┆         ┆         ┆           ┆           │
╞════════════╪════════════╪════════════╪═══════════╪═══╪═════════╪═════════╪═══════════╪═══════════╡
│ 2026-03-07 ┆ 2026-03-07 ┆ 31.22      ┆ 36.12     ┆ … ┆ 0.0     ┆ 0.0     ┆ Clouds    ┆ broken    │
│ 05:00:00   ┆ T05:00:00  ┆            ┆           ┆   ┆         ┆         ┆           ┆ clouds    │
│ 2026-03-09 ┆ 2026-03-09 ┆ 31.22      ┆ 35.32     ┆ … ┆ 0.0     ┆ 0.0     ┆ Clouds    ┆ broken    │
│ 05:00:00   ┆ T05:00:00  ┆            ┆           ┆   ┆         ┆         ┆           ┆ clouds    │
│ 2026-03-20 ┆ 2026-03-20 ┆ 30.36      ┆ 34.67     ┆ … ┆ 0.0     ┆ 0.0     ┆ Clouds    ┆ broken    │
│ 11:00:00   ┆ T11:00:00  ┆            ┆           ┆   ┆         ┆         ┆           ┆ clouds    │
└────────────┴────────────┴────────────┴───────────┴───┴─────────┴─────────┴───────────┴───────────┘

In [ ]:
# Merge departure flights with weather
# Departure: join dep_hour with weather_hour (not exceeding scheduled time means weather_hour <= dep_hour)
if len(departure_flights) > 0:
    merged_departures = departure_flights.join(
        weather_pdf,
        how='left',
        left_on='dep_hour',
        right_on='weather_hour',
        maintain_order='left'
    )
    print(f"Merged departure flights: {len(merged_departures)}") # will need to check this tmr

# Merge arrival flights with weather
# Arrival: join arr_hour with weather_hour (same hour)
if len(arrival_flights) > 0:
    merged_arrivals = arrival_flights.join(
        weather_pdf,
        how='left',
        left_on='arr_hour',
        right_on='weather_hour',
        maintain_order='left'
    )
    print(f"Merged arrival flights: {len(merged_arrivals)}")

# Combine both datasets
if len(merged_departures) > 0 and len(merged_arrivals) > 0:
    combined_flights = pl.concat([merged_departures, merged_arrivals], how='vertical') \
            .sort(by=['dep_scheduled_time', 'dep_actual_time', 'arr_scheduled_time', 'arr_actual_time'], nulls_last=True)
    # print(combined_flights.columns)
    combined_flights = combined_flights.drop(['id', 'insert_time', 'iata_number', 'airline_name', 'codeshared_airline', 'codeshared_flight_number'])
else:
    combined_flights = pl.DataFrame()

print(f"\n Combined flights with weather data: {len(combined_flights)} rows")
combined_flights.head(3)

Merged departure flights: 63390
Merged arrival flights: 62674
['id', 'insert_time', 'flight_type', 'status', 'iata_number', 'airline_name', 'dep_scheduled_time', 'dep_actual_time', 'dep_delay_mins', 'arr_scheduled_time', 'arr_actual_time', 'arr_delay_mins', 'codeshared_airline', 'codeshared_flight_number', 'dep_hour', 'arr_hour', 'date_observed', 'current_temp', 'feels_like_temp', 'pressure_hPa', 'humidity_pct', 'max_temp', 'min_temp', 'wind_speed_ms', 'wind_deg', 'cloudiness_pct', 'rain_1h', 'rain_3h', 'weather_main', 'weather_desc']

 Combined flights with weather data: 126064 rows

shape: (3, 24)
┌─────────────┬────────┬────────────┬────────────┬───┬─────────┬─────────┬────────────┬────────────┐
│ flight_type ┆ status ┆ dep_schedu ┆ dep_actual ┆ … ┆ rain_1h ┆ rain_3h ┆ weather_ma ┆ weather_de │
│ ---         ┆ ---    ┆ led_time   ┆ _time      ┆   ┆ ---     ┆ ---     ┆ in         ┆ sc         │
│ str         ┆ str    ┆ ---        ┆ ---        ┆   ┆ f64     ┆ f64     ┆ ---        ┆ ---        │
│             ┆        ┆ str        ┆ str        ┆   ┆         ┆         ┆ str        ┆ str        │
╞═════════════╪════════╪════════════╪════════════╪═══╪═════════╪═════════╪════════════╪════════════╡
│ arrival     ┆ landed ┆ 2026-02-27 ┆ 2026-02-27 ┆ … ┆ 0.0     ┆ 0.0     ┆ Clouds     ┆ broken     │
│             ┆        ┆ T14:35:00  ┆ T14:57:00  ┆   ┆         ┆         ┆            ┆ clouds     │
│ arrival     ┆ landed ┆ 2026-02-28 ┆ 2026-02-28 ┆ … ┆ 0.0     ┆ 0.0     ┆ Clouds     ┆ broken     │
│             ┆        ┆ T00:45:00  ┆ T01:18:00  ┆   ┆         ┆         ┆            ┆ clouds     │
│ arrival     ┆ landed ┆ 2026-02-28 ┆ 2026-02-28 ┆ … ┆ 0.0     ┆ 0.0     ┆ Clouds     ┆ broken     │
│             ┆        ┆ T01:35:00  ┆ T02:03:00  ┆   ┆         ┆         ┆            ┆ clouds     │
└─────────────┴────────┴────────────┴────────────┴───┴─────────┴─────────┴────────────┴────────────┘